# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install packages
        run: yarn install --immutable

      # - name: Generate stack
      #   run: npx nx g serverless test-stack

      # - name: Generate library
      #   run: npx nx g @nx/node:lib test-lib --tags lib

      - name: Linting
        run: npx nx run-many --target=lint --all

      # - name: Run tests
      #   run: npx nx run-many --target=test --all

      - name: Sls package
        run: npx nx run my-nest-app:build --stage=dev

      - name: Sls deploy
        run: npx nx run my-nest-app:deploy --stage=dev
